### ISSUE TITLE
(RING_SIZE << 6)

### ISSUE THREAD

**Issue by richardm292** [robert-hh/RP2040-Examples#2]
should (RING_SIZE << 9) be (RING_SIZE << 6) ?

...actually I need to test.  yes got it to work with RING_SIZE << 6.

**Comment by robert-hh** [comment]
RING_SIZE << 6 is right. It did not matter since both RINGS_SIZE and RING_SEL and CHAIN_TO were 0.

**Comment by robert-hh** [comment]
Fixed.
