### ISSUE TITLE
Question: 10 megabit UART?

### ISSUE THREAD

**Issue by rlabs-oss** [robert-hh/RP2040-Examples#3]
Hi,
    Is it possible to configure one of the UART's for 10 mbit baudrate? The picoboard reports an actual value of 7812500 when attempting this and I would like to reach 10,000,000 on the UART to interface with a camera. Preferably both uart and uart over usb speeds match to transfer from the uart to usb.

Thank you,
-M

**Comment by robert-hh** [comment]
I have tested the UART up to 5.5296 Mbit using the PR for buffered UART. At twice the speed it did not work any more. Even at higher clock frequencies. It could be a problem of the UART clock setting. Without that PR, the standard UART class only buffers 32 bytes.  That would be the practical limit then. 

Besides that, questions like yours are better raised on the forum http://forum.micropython.org. It has a larger community.

**Comment by rlabs-oss** [comment]
> Besides that, questions like yours are better raised on the forum http://forum.micropython.org. It has a larger community.

Thank you will check there.
